esphome:
  name: consumo-taller
  friendly_name: consumo taller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5a7ylqqQWd+4bjubjjdxh/J1QqdqpHFmu+KHfVmxxjw="

ota:
  - platform: esphome
    password: "4686ee2280d4eb60c650e8c703e75b0e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Consumo-Taller Fallback Hotspot"
    password: "YF7m6DCUiFrW"

captive_portal:
    
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1
  
sensor:
  - platform: pzemac
    current:
      name: "consumo-taller Current"
    voltage:
      name: "consumo-taller Voltage"
    energy:
      name: "consumo-taller Energy"
    power:
      name: "consumo-taller Power"
    frequency:
      name: "consumo-taller Frequency"
    power_factor:
      name: "consumo-taller Power Factor"
    update_interval: 2s

bluetooth_proxy:
  active: true