# Board: M5Stack Dial
# Definition: definitions/boards/m5stack_dial/manifest.yaml

esphome:
  name: m5stackdial
  friendly_name: M5stackDial

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "LYOyak5NwU4Bvn/CgYd2zYqjmpGUhppS3BgmIDmyr30="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: M5stackDial Fallback Hotspot
    password: "OV9iCFZdCE5Y"

captive_portal:

output:
  - platform: ledc
    id: backlight_output
    pin: 9
  - platform: ledc
    id: buzzer
    pin: 3

light:
  - platform: monochromatic
    name: Backlight
    id: display_backlight
    default_transition_length: 0s
    output: backlight_output

spi:
  - id: spi_bus
    clk_pin: 6
    mosi_pin: 5

i2c:
  - id: internal_i2c
    scl: 12
    sda: 11

binary_sensor:
  - platform: gpio
    name: Button
    id: front_button
    pin: 42
  - platform: gpio
    name: Hold Button
    id: binary_sensor_gpio_2
    pin: 46
