esphome:
  name: bluetooth-tracker-dormitorio
  friendly_name: bluetooth-tracker-dormitorio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LVjTKrmj1kxbO2VSxRtZxxZB6tNXcdKoGH2VSErJbu0="

ota:
  - platform: esphome
    password: "a5bf02f8daefbde2ae2ec5100c4a52d0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Tracker-Dormitorio"
    password: "NIFUqG7FK4BN"

captive_portal:

esp32_ble_tracker:
  scan_parameters: 
    active: True
bluetooth_proxy:
  active: True